### ISSUE TITLE
Improve renderAsync

### ISSUE THREAD

**Issue by ForbesLindesay** [jstransformers/jstransformer-browserify#10]
Looking at https://github.com/substack/node-browserify/blob/master/bin/cmd.js#L30 it looks like we could make the render method work without using browserify-string.  This would also have the advantage of removing the need for a temporary empty file.

**Comment by RobLoach** [comment]
:+1:

**Comment by hemanth** [comment]
:+1:

**Comment by RobLoach** [comment]
@ForbesLindesay I'm having troubles figuring this out. Did you do something similar for `middlewares`?

**Comment by ForbesLindesay** [comment]
I haven't tried anything similar before.  It looks like it should be possible to pipe a string to browserify though.
