### ISSUE TITLE
working in pug

### ISSUE THREAD

**Issue by coachshea** [jstransformers/jstransformer-browserify#25]
I am attempting to use this transform in a pug project and I keep receiving an error because there is no synchronous methods on jstranformer-browserify. I had mistakenly placed this issue with the pug repositiory and I received the following suggestion from drooney, I include it hear because I think it might be helpful.

jstransformer requires a transformer to expose a renderSync or/and render methods, and the latter doesn't exist in jstransformer-browserify because browserify uses streams which are asynchronous. I suggest you suggest there that they expose the syncronous method which can be implemented using child_process.execSync(), for instance.

**Comment by RobLoach** [comment]
There is no syncronous function for Browserify. There may be a third-party one, however. Mind having a look to see if that's possible?

**Comment by coachshea** [comment]
I haven’t been able to find anything so far, but I’ll see what I can do.

--
John Shea
Cell: 617-605-5763
Email: coachshea@fastmail.com

**Comment by droooney** [comment]
As I said in [this issue](https://github.com/pugjs/pug/issues/2930), [`child_process.execSync()`](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options) can be used for such purpose. I can probably submit a PR later :)
